"project_id": "CROWDIN_PROJECT_ID"
"api_token": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true

files: [
  {
    "source": "app/_locales/en/*.json",
    "translation": "app/_locales/%two_letters_code%/%original_file_name%",
    "update_option": "update_as_unapproved"
  }
]
