name: Crowdin - Branch and Label Cleanup for merged localization PR
# This action should delete the branch from Crowdin after the localization PR is 
# merged to the original branch. It should also remove the "ready-for-translation" label

# TODO: Add trigger for merge of localization PR.
on: workflow_dispatch

jobs:
  prestep:
    runs-on: ubuntu-latest
    steps:
      - name: Extract current branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_current_branch

  github_cleanup:
    runs-on: ubuntu-latest
    needs: prestep
    steps:
      - name: Remove label from PR
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.payload.pull_request.number;
            const label = "ready-for-translation";
            await github.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              name: label
            });
  crowdin_cleanup:
    runs-on: ubuntu-latest
    needs: prestep
    steps:
      - name: Delete branch within Crowdin
        if: ${{ steps.extract_current_branch.outputs.branch }} != 'main'
        uses: crowdin/github-action@c858c54aca1629608ec39a54ee0f7ba4389eb59f
        with:
          # on crowdin not GH
          command: delete branch 
          command_args: ${{ steps.extract_current_branch.outputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
