name: Crowdin - Branch and Label Cleanup for merged localization PR
# This action should delete the branch from Crowdin after the localization PR is 
# merged to the original branch. It should also remove the "ready-for-translation" label

# TODO: Add trigger for merge of localization PR.
on: workflow_dispatch

jobs:
  prestep:
    runs-on: ubuntu-latest
    steps:
      - name: Extract current branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_current_branch

  github_cleanup:
    runs-on: ubuntu-latest
    needs: prestep
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Get PR with Label for this branch
        id: get-prs
        run: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          
          LABEL="ready-for-translation"
          API_URL="https://api.github.com/repos/Metamask/crowdin-sandbox/pulls?head:${{steps.extract_current_branch.outputs.branch}}&state=open&per_page=100"
          
          # Fetch the list of open pull requests with the specified label using curl
          PRS=$(curl -sS --header "Authorization: Bearer $GITHUB_TOKEN" "$API_URL")
          
          PR=$(echo $PRS | jq -r '.[] | select(.labels[].name == "ready-for-translation") | .number | @json')
          echo "Found PR: $PR"
          echo "pr=$PR" >> $GITHUB_OUTPUT

      - name: Remove label from PR
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const label = "ready-for-translation";
            await github.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.get-prs.outputs.pr }},
              name: label
            });
  crowdin_cleanup:
    runs-on: ubuntu-latest
    needs: prestep
    steps:
      - name: Delete branch within Crowdin
        if: ${{ steps.extract_current_branch.outputs.branch }} != 'main'
        uses: crowdin/github-action@c858c54aca1629608ec39a54ee0f7ba4389eb59f
        with:
          # on crowdin not GH
          command: delete branch ${{ steps.extract_current_branch.outputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
