name: Branch Cleanup Crowdin Action

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    types:
      - closed

jobs:
  prestep:
    runs-on: ubuntu-latest
    steps:
      - name: Extract current branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_current_branch
  if_merged:
    if: github.event.pull_request.merged == true && github.event.pull_request.title == ' New Crowdin translations for ${{ needs.prestep.outputs.branch }}'
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
  crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Extract current branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_current_branch
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Delete branch within Crowdin
        uses: crowdin/github-action@a3160b9e5a9e00739392c23da5e580c6cabe526d
        with:
          delete_crowdin_branch: ${{ steps.extract_current_branch.outputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}