name: Crowdin - Branch Cleanup for merged translation branches - Crowdin Action
# This action should cleanup any internationalization branches for associated merged PRs
# in github and should delete the created branch in crowdin.

on: workflow_dispatch

jobs:
  prestep:
    runs-on: ubuntu-latest
    steps:
      - name: Extract current branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_current_branch
  if_merged:
    if: github.event.pull_request.merged == true && github.event.pull_request.title == 'New Crowdin translations for ${{ needs.prestep.outputs.branch }}'
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
  crowdin_cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch within Crowdin
        if: ${{ steps.extract_current_branch.outputs.branch }} != 'main'
        uses: crowdin/github-action@c858c54aca1629608ec39a54ee0f7ba4389eb59f
        with:
          command: delete branch 
          command_args: ${{ steps.extract_current_branch.outputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

  gh_cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Delete branch within GitHub
        if: ${{ steps.extract_current_branch.outputs.branch }} != 'main'
        run: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          
          API_URL="https://api.github.com/repos/Metamask/crowdin-sandbox/git/refs/heads/l10n_crowdin_translations_${{ steps.extract_current_branch.outputs.branch }}"

          curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" "$API_URL"    
          
          echo "Github branch: ${{ steps.extract_current_branch.outputs.branch }} deleted"
