name: Find all pull requests with ready-for-translation label
# Trying to figure out how to run a workflow for a set of branches

on: workflow_dispatch

jobs:
  get-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        uses: actions/checkout@v4

      - name: Get branches with "ready" label
        id: get-branches
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}

        run: |
          LABEL_NAME="ready-for-translation"
          BRANCHES=""
          while true; do
            PRS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" "https://api.github.com/repos/$REPO/pulls?state=open")
            if [[ -z "$PRS" ]]; then
              break
            fi
            BRANCHES="$BRANCHES $(echo "$PRS" | jq -r '.[].head.ref')"
          done
          echo "branches=${BRANCHES}" >> $GITHUB_OUTPUT
          

      - name: Show branches with "ready" label
        run: | 
          echo "Branches with 'ready' label: ${{ steps.get-branches.outputs.branches }}"
          

