name: Find all pull requests with ready-for-translation label
# Trying to figure out how to run a workflow for a set of branches

on: workflow_dispatch

jobs:
  get-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        uses: actions/checkout@v4

      - name: Get branches with "ready" label
        id: get-branches
        run: |
          LABEL_NAME="ready"
          BRANCHES=""
          for branch in $(git branch -r --format='%(refname:lstrip=3)'); do
            if [[ $(git log -1 --pretty=%B $branch) =~ $LABEL_NAME ]]; then
              BRANCHES="$BRANCHES $branch"
            fi
          done
          echo "branches=${BRANCHES}" >> $GITHUB_OUTPUT

      - name: Show branches with "ready" label
        run: | 
          echo "Branches with 'ready' label: ${{ steps.get-branches.outputs.branches }}"
          

