name: Find all pull requests with ready-for-translation label
# Trying to figure out how to run a workflow for a set of branches

on: workflow_dispatch

jobs:
  get-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        uses: actions/checkout@v4

      - name: Get branches with "ready" label
        id: get-branches
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}

        run: |
          LABEL_NAME="ready-for-translation"
          BRANCHES=""
          PRS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" "https://api.github.com/search/issues?q=org:MetaMask+repo:crowdin-sandbox+is:pr+is:open+label:${LABEL_NAME}")
          echo "prs=$PRS"
          BRANCHES="$(echo "$PRS" | jq -r '.[].head.ref')"
          echo "branches=$BRANCHES"       

      - name: Show branches with "ready" label
        run: | 
          echo "Branches with 'ready-for-translation' label: ${{ steps.get-branches.outputs.branches }}"
          

