name: Find all pull requests with ready-for-translation label
# Trying to figure out how to run a workflow for a set of branches

on: workflow_dispatch

jobs:
  get-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Branches with Label
        id: get-branches
        run: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          
          LABEL="ready-for-translation"
          API_URL="https://api.github.com/repos/Metamask/crowdin-sandbox/pulls?state=open&per_page=100"
          
          # Fetch the list of open pull requests with the specified label using curl
          PRS=$(curl -sS --header "Authorization: Bearer $GITHUB_TOKEN" "$API_URL")


          echo "jq1 output: $(echo $PRS | jq -r '.[] | .labels[].name')"
          echo "jq2 output: $(echo $PRS | jq -r '.[] | select(.labels[].name == "ready-for-translation")')"
          BRANCHES=$($PRS | jq -r '.[] | select(.labels[].name == "$LABEL") | .head.ref')
          
          echo "Branches with the label '$LABEL':"
          echo "$BRANCHES"
          
          echo "branches=$BRANCHES" >> $GITHUB_OUTPUT

      - name: Display Branches
        run: |
          BRANCHES="${{ steps.get-branches.outputs.branches }}"
          echo "Unique Branches: $BRANCHES"