name: Push for translations - Crowdin Action

# When an individual is working on a feature which requires translations, they can
# add a label "ready-for-translation" which will trigger this action to push the 
# source and translation files to Crowdin. We will always push main as the base of
# the crowdin branch creation and then push in the changes over the top. This ensures
# that the translations which have already been done and approved previously do not
# show as needing to be translated again in crowdin.

on: 
  pull_request:
    types: [labeled]
   
jobs:
  crowdin-upload:
    if: github.event.label.name == 'ready-for-translation'
    runs-on: ubuntu-latest
    steps:
      - name: Extract current branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_current_branch
      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      
      - name: Crowdin push
        uses: crowdin/github-action@a3160b9e5a9e00739392c23da5e580c6cabe526d
        with:
          crowdin_branch_name: ${{ steps.extract_current_branch.outputs.branch }}
          upload_sources: true
          upload_translations_args: --import-eq-suggestions --auto-approve-imported --verbose
          upload_translations: true
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
      
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.extract_current_branch.outputs.branch }}
      - name: Crowdin sources push
        uses: crowdin/github-action@a3160b9e5a9e00739392c23da5e580c6cabe526d
        with:
          crowdin_branch_name: ${{ steps.extract_current_branch.outputs.branch }}
          upload_sources: true
          upload_sources_args: --auto-update --verbose
          upload_translations: false
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}