name: Crowdin - Check translation progress and download if complete
# This is a reusable workflow that is called by pull_completed_translations across
# all branches which have a label of "ready-for-translation" aka being translated.
# This workflow will check the translation progress and download the translations if
# they are 100% translated.


permissions:
  contents: write
  pull-requests: write

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
    secrets:
      gh_token:
        required: true
      crowdin_project_id: 
        required: true
      crowdin_personal_token:
        required: true

jobs:
  crowdin:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.gh_token }}
      CROWDIN_PERSONAL_TOKEN: ${{ secrets.crowdin_personal_token }}
      CROWDIN_PROJECT_ID: ${{ secrets.crowdin_project_id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
      
      - name: Check translation progress
        uses: crowdin/github-action@c858c54aca1629608ec39a54ee0f7ba4389eb59f
        with:
          command: 'status translation'
          command_args: '-b ${{ inputs.branch }} --fail-if-incomplete'

      - name: Synchronize with Crowdin
        uses: crowdin/github-action@c858c54aca1629608ec39a54ee0f7ba4389eb59f
        with:
          crowdin_branch_name: ${{ inputs.branch }}
          upload_sources: false
          upload_translations: false
          download_translations: true
          skip_untranslated_strings: true
          export_only_approved: true
          localization_branch_name: l10n_crowdin_translations_${{ inputs.branch }}

          create_pull_request: true
          pull_request_title: New Crowdin translations for ${{ inputs.branch }}
          pull_request_body: New Crowdin pull request with translations for ${{ inputs.branch }}
          pull_request_base_branch_name: ${{ inputs.branch }}
