name: Upload sources Crowdin Action (happen on changes to en json only)

on: 
  push:
    paths:
      - 'src/_locales/en/messages.json'

jobs:
  prestep:
    runs-on: ubuntu-latest
    steps:
      - name: Extract current branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_current_branch

  crowdin-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Crowdin push
        uses: crowdin/github-action@a3160b9e5a9e00739392c23da5e580c6cabe526d
        with:
          crowdin_branch_name: ${{ steps.extract_current_branch.outputs.branch }}
          upload_sources: true
          upload_translations: true
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
      